### ISSUE TITLE
Tests have timezone issue

### ISSUE THREAD

**Issue by bufke** [torchbox/django-modelcluster#18]
Pretty minor issue - but two of the tests fail for me due to different timezones. Running tests with `python runtests.py`

```
======================================================================
FAIL: test_deserialise_with_utc_datetime (tests.tests.test_serialize.SerializeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/tests/tests/test_serialize.py", line 177, in test_deserialise_with_utc_datetime
    self.assertEqual(log.time, expected_time)
AssertionError: datet[21 chars] 1, 16, 1, 42, tzinfo=<django.utils.timezone.L[34 chars]e80>) != datet[21 chars] 1, 11, 1, 42, tzinfo=<django.utils.timezone.L[34 chars]e80>)

======================================================================
FAIL: test_serialise_with_naive_datetime (tests.tests.test_serialize.SerializeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/tests/tests/test_serialize.py", line 144, in test_serialise_with_naive_datetime
    self.assertEqual(log_json['time'], '2014-08-01T16:01:42Z')
AssertionError: '2014-08-01T11:01:42Z' != '2014-08-01T16:01:42Z'
- 2014-08-01T11:01:42Z
?             ^
+ 2014-08-01T16:01:42Z
?             ^
```

**Comment by gasman** [comment]
It appears that these tests only work when pytz is installed - have replicated this failure by installing in a fresh virtualenv without pytz. Rather than dig into the root cause, I've decided to take the easy route and specify pytz as a dependency in 421c28b295b59583eaad1d58de84a6350b883e2c :-)
